name: flutter_base
description: "LearnX - A professional mobile learning marketplace."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2

  google_fonts: ^8.0.1
  modal_bottom_sheet: ^3.0.0
  
  # State & Storage
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  dio: ^5.9.0
  get_it: ^9.2.0
  flutter_dotenv: ^6.0.0
  video_player: ^2.10.1
  chewie: ^1.13.0
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true # Check this for l10n generation

  assets:
    - .env
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

